### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by RaulPPelaez** [mudler/LocalAGI#10]
When trying to spin up the project for the first time I eventually get the following error from Chroma.
```shell
$ docker-compose up
[+] Running 1/0
 ✔ Container localagi-api-1  Running                                                                                                                                    0.0s 
Attaching to api-1, localagi-1
localagi-1  | /usr/local/lib/python3.10/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
localagi-1  | 
localagi-1  | `from langchain_community.embeddings import LocalAIEmbeddings`.
localagi-1  | 
localagi-1  | To install langchain-community run `pip install -U langchain-community`.
localagi-1  |   warnings.warn(
localagi-1  | /usr/local/lib/python3.10/site-packages/langchain/vectorstores/__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
localagi-1  | 
localagi-1  | `from langchain_community.vectorstores import Chroma`.
localagi-1  | 
localagi-1  | To install langchain-community run `pip install -U langchain-community`.
localagi-1  |   warnings.warn(
localagi-1  | Traceback (most recent call last):
localagi-1  |   File "/app/./main.py", line 154, in <module>
localagi-1  |     chroma_client = Chroma(collection_name="memories", persist_directory="db", embedding_function=embeddings)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 120, in __init__
localagi-1  |     self._client = chromadb.Client(_client_settings)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 248, in Client
localagi-1  |     return ClientCreator(tenant=tenant, database=database, settings=settings)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/api/client.py", line 139, in __init__
localagi-1  |     super().__init__(settings=settings)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/api/client.py", line 43, in __init__
localagi-1  |     SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/api/client.py", line 56, in _create_system_if_not_exists
localagi-1  |     new_system.start()
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/config.py", line 387, in start
localagi-1  |     component.start()
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
localagi-1  |     return f(*args, **kwargs)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/impl/sqlite.py", line 97, in start
localagi-1  |     with self.tx() as cur:
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/impl/sqlite.py", line 131, in tx
localagi-1  |     return TxWrapper(self._conn_pool, stack=self._tx_stack)
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/impl/sqlite.py", line 31, in __init__
localagi-1  |     self._conn = conn_pool.connect()
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/impl/sqlite_pool.py", line 141, in connect
localagi-1  |     new_connection = Connection(
localagi-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/impl/sqlite_pool.py", line 20, in __init__
localagi-1  |     self._conn = sqlite3.connect(
localagi-1  | pysqlite3.dbapi2.OperationalError: unable to open database file
localagi-1 exited with code 1
api-1       | [127.0.0.1]:57890 200 - GET /readyz
```

I have no idea what to do about it. Any guidance would be great!

**Comment by mudler** [comment]
code changed drammatically. this lost context and not relevant anymore.
