### ISSUE TITLE
Modified main.py:158 'get_avatar()'

### ISSUE THREAD

**Issue by KenDingel** [mudler/LocalAGI#5]
Based on localagi.py, the following function has two arguments
`def get_avatar(self, input_text)`

In main.py line 158, the call of that function is
```
def display_avatar(agi, input_text=STABLEDIFFUSION_PROMPT, model=STABLEDIFFUSION_MODEL):
    image_url = agi.get_avatar(input_text, model)
```
    
Which leads the the following error 
 ```
✔ Container localagi-api-1  Started                                                                          0.3s
2023-09-24 12:50:03.117 | INFO     | __main__:<module>:366 - Creating LocalAGI instance
2023-09-24 12:50:03.117 | INFO     | __main__:<module>:387 - Welcome to LocalAGI
2023-09-24 12:50:03.117 | INFO     | __main__:<module>:391 - Creating avatar, please wait...
Traceback (most recent call last):
  File "/app/./main.py", line 392, in <module>
    display_avatar(localagi)
  File "/app/./main.py", line 158, in display_avatar
    image_url = agi.get_avatar(input_text, model)
TypeError: LocalAGI.get_avatar() takes 2 positional arguments but 3 were given
```

I modified the line to 
`image_url = agi.get_avatar(input_text)`

Building the container now, will update on the result. 
UPDATE: IT WORKED, but I had to change something else too in get_avatar
```api_base=self.api_base+"/v1"``` There was a typo

**Comment by mudler** [comment]
code changed drammatically. this lost context and not relevant anymore.
